### ISSUE TITLE
Import existing resources not always possible by name

### ISSUE THREAD

**Issue by olga-mir** [olga-mir/playground#11]
Example with `Team` resource. It is highly likely that there are other resources that require numerical ID, which is dynamically created by Github at the time of resource creation and is not known at the composition rendering time.

### Config: 
```yaml
              # The external-name for a GitHub Team managed by this provider is the team's slug.
              # This patch ensures that for both creation of new teams and import of existing teams,
              # the external-name is correctly set to the team slug specified in the TeamConfig.
              - type: FromCompositeFieldPath
                fromFieldPath: spec.teamName
                toFieldPath: metadata.annotations["crossplane.io/external-name"]
```

### Error
```
        observe failed: failed to observe the resource: [{0 Unexpected ID format
        ("team-bravo"), expected numerical ID. strconv.ParseInt: parsing
        "team-bravo": invalid syntax  []}]
```

### Config:

As above but external-name was not provided at all in the composition. 
```yaml
#              - type: FromCompositeFieldPath
#                fromFieldPath: spec.teamName
#                toFieldPath: metadata.annotations["crossplane.io/external-name"]
```

### Error:

```
async create failed: failed to create the resource: [{0 POST https://api.github.com/orgs/tornado-demo/teams: 422 Validation Failed [{Resource:Team Field:data Code:unprocessable Message:Name must be unique for this org}] []}]
```

If we can't fish out existing team by its name slug (`team-bravo`) then there is no quick way to solve this in composition. 

Possible solutions: 
1. Prefetch numerical IDs and expose the field in XRD. Not ideal
2. Implement dedicated function that will fetch the IDs and feed them in.

Team ID can be retrieved with this call (or REST API):

```bash
$ gh api \    
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /orgs/tornado-demo/teams/team-bravo
```

**Comment by olga-mir** [comment]
```yaml
apiVersion: team.github.upbound.io/v1alpha1
kind: Team
metadata:
  annotations:
    crossplane.io/composition-resource-name: team
    crossplane.io/external-name: team-bravo
  creationTimestamp: '2025-06-22T04:28:31Z'
  generation: 1
  labels:
    crossplane.io/claim-name: ''
    crossplane.io/claim-namespace: ''
    crossplane.io/composite: team-bravo
  name: team-bravo
  ownerReferences:
    - apiVersion: platform.tornado-demo.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: TeamConfig
      name: team-bravo
spec:
  deletionPolicy: Delete
  forProvider:
    description: Bravo Team - managed by Crossplane
    name: team-bravo
    privacy: closed
  managementPolicies:
    - '*'
  providerConfigRef:
    name: github-provider-org-lvl
status:
  atProvider: {}
  conditions:
    - lastTransitionTime: '2025-06-22T04:28:32Z'
      message: >-
        observe failed: failed to observe the resource: [{0 Unexpected ID format
        ("team-bravo"), expected numerical ID. strconv.ParseInt: parsing
        "team-bravo": invalid syntax  []}]
      reason: ReconcileError
      status: 'False'
      type: Synced
```
