### ISSUE TITLE
Crossplane Github provider: importing existing resource constantly updates `external-name` value

### ISSUE THREAD

**Issue by olga-mir** [olga-mir/playground#9]
Importing existing `RepositoryFile` using `external-name` leads to constant updating of the MR. 

Example:

```yaml
apiVersion: repo.github.upbound.io/v1alpha1
kind: RepositoryFile
metadata:
  annotations:
    crossplane.io/composition-resource-name: codeowners-file
    crossplane.io/external-create-failed: "2025-06-15T02:28:41Z"
    crossplane.io/external-create-pending: "2025-06-15T02:28:41Z"
    crossplane.io/external-create-succeeded: "2025-06-15T02:27:42Z"
    crossplane.io/external-name: service-xyz:CODEOWNERS.md:main
    crossplane.io/resource-policy: Orphan
  creationTimestamp: "2025-06-15T02:27:40Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
```

Diff with a resource captured in another moment:

```diff
9c9
<     crossplane.io/external-name: service-xyz:CODEOWNERS.md:main
---
>     crossplane.io/external-name: service-xyz/CODEOWNERS.md
```

The resource transitions between these two states endlessly.

This is relevant composition snippet at the time when this behaviour was observed:

```yaml
        # Patch for external-name: repository_slug:file_path:branch_name
        # Assuming default branch is 'main' if not specified elsewhere for this file.
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.serviceName # or spec.name
              - fromFieldPath: spec.settings.defaultBranch # Fallback to 'main' if not set
            strategy: string
            string:
              fmt: "%s:CODEOWNERS.md:%s" # Uses spec.settings.defaultBranch or you can hardcode 'main'
          toFieldPath: metadata.annotations["crossplane.io/external-name"]
          policy:
            fromFieldPath: Optional
```
